version: '3.8'

services:
  video-frame-extractor:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
      # Mount common host directories to container
      - ~/Downloads:/app/mounts/Downloads
      - ~/Desktop:/app/mounts/Desktop  
      - ~/Documents:/app/mounts/Documents
      - ~/Movies:/app/mounts/Movies
      # Allow custom mount point
      - ${CUSTOM_OUTPUT_PATH:-~/output}:/app/mounts/Custom
    environment:
      - NODE_ENV=production